Added style for hw1
ok-technopolis-2020/Sakhibgareev_Ramis pull request #2
Opened 2020-10-22 19:49 UTC by rapturemain

2020-10-23 12:56 UTC, fromanywhere requested changes
not bad

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    margin-top: 15%;
ну, нет, точно не проценты

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    width: 480px;
не по макету

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    width: fit-content;
зачем так?

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    letter-spacing: -6px;
не надо так делать

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    font-family: Montserrat;
Roboto, sans-serif

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    letter-spacing: -1px;
нет

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +.todos_list li button {
зачем такой каскад? стремимся к плоскому списку классов

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    -ms-transform: scale(1.5); /* IE */
префиксы не нужны

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +.todos_list li:hover button {
фокус потерялся

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    border: lightgray solid 1px;
ну, предполагается, что обводка есть только у активного

2020-10-23 12:56 UTC, fromanywhere commented on style.css
> +    background-color: rgb(245, 245, 245);
но в хексе же проще?

2020-10-29 21:51 UTC, rapturemain commented on style.css
> +    background-color: rgb(245, 245, 245);
Я устанавливал цвета через палитру в IDE (в цветовом круге, а значения в десятичной само ставилось)

2020-10-30 10:16 UTC, fromanywhere requested changes
Почти хорошо

2020-10-30 10:16 UTC, fromanywhere commented on index.html
> +                <li class="todo">
последний пустой элемент просвечивает ховером и кнопкой удаления, хотя не должен

2020-10-30 10:16 UTC, fromanywhere commented on style.css
> +    margin-top: 150px;
тут нужно подумать про более аккуратное выравнивание, на мобилке необоснованная дырка сверху будет

2020-10-30 10:16 UTC, fromanywhere commented on style.css
> +header h1 {
все селекторы переписываем на бэм, в плоскую структуру классов

2020-11-10 17:39 UTC, fromanywhere approved these changes

2020-11-10 17:44 UTC, merged